### ISSUE TITLE
Bitmap Error

### ISSUE THREAD

**Issue by RedwanSharafatKabir** [AppcentMobile/removebg#6]
remover.clearBackground(inputImage.value).collect { output ->
    outputImage.value = output
}

This piece of code gives this error: "unable to getPixels(), pixel access is not supported on Config#HARDWARE bitmaps"

What should I do?

**Comment by erenalpaslan** [comment]
Hi @RedwanSharafatKabir, i couldn't reproduce the issue but i added an extra step to make the given bitmap mutable. So you can try the version 1.0.4 or you can just pass a mutable bitmap to ```clearBackground``` method 
For making mutable bitmap
```
bitmap.copy(Bitmap.Config.ARGB_8888, true)
```
